version: 2
jobs:
  build:
    
    working_directory: ~/circleci-test-java

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - run : ll

      - restore_cache:
          key: circleci-test-java-{{ checksum "pom.xml" }}
      
      - run: mvn -X dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-test-java-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/circleci-test-java-0.0.1-SNAPSHOT.jar
